---

# Setup/install tasks.
- name: Load setup-RedHat Tasks
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Load setup-Debian Tasks
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'